"""Init

Revision ID: caafff05c6f1
Revises: 6de534cd82e2
Create Date: 2023-01-15 21:18:38.447457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "caafff05c6f1"
down_revision = "6de534cd82e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
