"""Init

Revision ID: f8beaba7873b
Revises: f072ecfb6b29
Create Date: 2023-01-16 00:26:35.429386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8beaba7873b"
down_revision = "f072ecfb6b29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
