"""Init

Revision ID: ff5016b4d877
Revises: caafff05c6f1
Create Date: 2023-01-15 21:24:42.031248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff5016b4d877"
down_revision = "caafff05c6f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
